version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: runner
    container_name: storm_app
    restart: always
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
    image: postgres:13.1
    container_name: storm_postgres_prod
    restart: always
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    # init db script will be only executed 
    # when the container runs the first time
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
