version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: runner
    container_name: storm_app
    restart: always
    environment:
      # default envs postgrex is looking for
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:13.1
    container_name: storm_postgres_prod
    restart: always
    environment:
      # default envs postgres is looking for
      - POSTGRES_HOST=${PGHOST}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - "5432:5432"
    # init db script will be only executed 
    # when the container runs the first time
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db:

